---
title: "Mini-Project 2"
author: "Amelia Stapleton and Cassie Naranjo"
date: "2019-03-24"
output: 
  html_document:
    code_folding: show
---

```{r, message = FALSE, echo = FALSE}
## Loading the data
library(tidyverse)
library(dplyr)
library(ggthemes)
library(RColorBrewer)
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, message = FALSE, echo = FALSE}
##Filtering out what we want from candidates data.frame
new_c <- candidates %>%
  filter(cand_election_yr == "2012") %>%
  select(cand_id,cand_election_yr)
```

```{r, message = FALSE, echo = FALSE}
##Filtering out what we want from house_elections data.frame
##Mutating to create a common variable
new_h_e <- house_elections %>%
  filter(incumbent == "TRUE") %>%
  mutate(cand_id = fec_id) %>%
  select(cand_id, candidate_name, state, incumbent, party, ge_winner)
```

```{r, message = FALSE, echo = FALSE}
##Joining tables
MP2_table <- new_h_e %>%
  inner_join(new_c, by = c("cand_id" = "cand_id"))
```

```{r message = FALSE, echo = FALSE}
##Creating a function for tables
table_function <- function(state_arg) {
  MP2_table %>%
     filter(state == state_arg) %>%
  group_by(party, ge_winner) %>%
  summarize(N = n())
}
```

```{r, message = FALSE, echo = FALSE}
##State Arguments
plot_CA <- table_function(state_arg = "CA")
plot_NY <- table_function(state_arg = "NY")
plot_TX <- table_function(state_arg = "TX")
```

```{r, message = FALSE, echo = FALSE}
##Trying to create a function for graphics 
plot_function <- function(data_arg) {
  ggplot(data = data_arg, aes(x = party, y = N, fill = interaction(party, ge_winner))) +
  geom_bar(stat = "identity", position = "stack") +
  labs(y = "Number of Incumbent Candidates", x = "Political Party") +
    scale_fill_manual(values = c("#9ecae1", "#fc9272", "#3182bd", "#de2d26"), name = "Condition", labels = c("Democratic Nonwinner", "Republican Nonwinner", "Democratic Winner", "Republican Winner"))+
  scale_x_discrete(breaks = c("D", "R"), labels = c("Democratic", "Republican")) +
  ggthemes::theme_tufte() +
  theme(plot.title = element_text(size=16.5, face='bold'),
axis.title.x = element_text(size =14), axis.title.y = element_text(size = 14), axis.ticks.length = (unit(.20, "cm")))
}

```


```{r}
##Creating the graphics
plot_function(data_arg = plot_CA) +
  labs(title = "How Likely is a Candidate from California To Be Re-Elected?") +
  annotate("text", x = 1, y = 15, label = "87%", color = "white", size = 8, fontface = 'bold') +
  annotate("text", x = 2, y =7, label = "80%", color = "white", size = 8, fontface = 'bold')

plot_function(data_arg = plot_NY) +
  labs(title = "How Likely is a Candidate from New York To Be Re-Elected?") +
  annotate("text", x = 1, y = 9, label = "94%", color = "white", size = 8, fontface = 'bold') +
  annotate("text", x = 2, y = 2.5, label = "71%", color = "white", size = 8, fontface = 'bold')

plot_function(data_arg = plot_TX) +
  labs(title = "How Likely is a Candidate from Texas To Be Re-Elected?") +
  annotate("text", x = 1, y = 4, label = "88%", color = "white", size = 8, fontface = 'bold') +
  annotate("text", x = 2, y = 12, label = "95%", color = "white", size = 8, fontface = 'bold')
```
